import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { useParams } from 'react-router-dom'

import { Badge, type BadgeProps } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { acknowledgeDisclaimer, getDocument } from '@/api/documents'
import type { DocumentStatus } from '@/types'

const SEVERITY_VARIANT: Record<string, BadgeProps['variant']> = {
  high: 'destructive',
  medium: 'default',
  low: 'muted',
}

const IN_PROGRESS_STATUSES = new Set<DocumentStatus>([
  'uploaded',
  'extracting',
  'extracted',
  'reviewing',
])

export default function DocumentDetail() {
  const { id } = useParams<{ id: string }>()
  const queryClient = useQueryClient()

  const { data: document } = useQuery({
    queryKey: ['documents', id],
    queryFn: () => getDocument(id!),
    enabled: !!id,
    refetchInterval: (query) =>
      query.state.data && IN_PROGRESS_STATUSES.has(query.state.data.status) ? 3000 : false,
  })

  const ackMutation = useMutation({
    mutationFn: () => acknowledgeDisclaimer(id!),
    onSuccess: () => queryClient.invalidateQueries({ queryKey: ['documents', id] }),
  })

  if (!document) {
    return <p className="text-sm text-muted-foreground">Loading…</p>
  }

  return (
    <div className="flex flex-col gap-6">
      <div>
        <h1 className="text-2xl font-semibold">{document.filename}</h1>
        <Badge variant={document.status === 'failed' ? 'destructive' : 'muted'} className="mt-2">
          {document.status}
        </Badge>
      </div>

      {document.instructions && (
        <p className="text-sm text-muted-foreground">
          <span className="font-medium text-foreground">Focus requested: </span>
          {document.instructions}
        </p>
      )}

      {document.status === 'failed' && (
        <p className="text-sm text-destructive">{document.failure_reason}</p>
      )}

      {!document.review && document.status !== 'failed' && (
        <p className="text-sm text-muted-foreground">Review in progress…</p>
      )}

      {document.review && (
        <>
          <Card className="border-amber-500/50 bg-amber-500/5">
            <CardContent className="pt-6">
              <p className="text-sm text-muted-foreground">
                This review is generated by AI for informational purposes only. It is not legal
                or financial advice and does not replace review by a qualified lawyer or
                accountant. Verify all flagged risks and suggested language with a professional
                before relying on them.
              </p>
              {!document.review.disclaimer_ack && (
                <Button
                  size="sm"
                  className="mt-3"
                  disabled={ackMutation.isPending}
                  onClick={() => ackMutation.mutate()}
                >
                  I understand
                </Button>
              )}
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>Executive summary</CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-sm">{document.review.executive_summary}</p>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>Risk flags</CardTitle>
            </CardHeader>
            <CardContent className="flex flex-col gap-3">
              {document.review.risk_flags.length === 0 ? (
                <p className="text-sm text-muted-foreground">No risks flagged.</p>
              ) : (
                document.review.risk_flags.map((flag, i) => (
                  <div key={i} className="flex flex-col gap-1 rounded-md border p-3">
                    <div className="flex items-center gap-2">
                      <Badge variant={SEVERITY_VARIANT[flag.severity] ?? 'muted'}>
                        {flag.severity}
                      </Badge>
                      <span className="text-sm font-medium">{flag.category}</span>
                    </div>
                    <p className="text-sm text-muted-foreground">{flag.description}</p>
                  </div>
                ))
              )}
            </CardContent>
          </Card>

          {document.review.suggested_rewrite && (
            <Card>
              <CardHeader>
                <CardTitle>Suggested rewrite</CardTitle>
              </CardHeader>
              <CardContent>
                <p className="whitespace-pre-wrap text-sm">{document.review.suggested_rewrite}</p>
              </CardContent>
            </Card>
          )}
        </>
      )}
    </div>
  )
}
