"""add email is_hidden

Revision ID: 218d1d6c7c28
Revises: 9723613b17b9
Create Date: 2026-07-16 19:59:26.560122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '218d1d6c7c28'
down_revision: Union[str, None] = '9723613b17b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'email_messages',
        sa.Column('is_hidden', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_messages', 'is_hidden')
    # ### end Alembic commands ###
