"""add document instructions

Revision ID: 5e1aabd2391f
Revises: 0f0d00c3b2b3
Create Date: 2026-07-07 19:53:56.433949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e1aabd2391f'
down_revision: Union[str, None] = '0f0d00c3b2b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('instructions', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'instructions')
    # ### end Alembic commands ###
