"""add email accounts messages extend drafts

Revision ID: 8fcebbdf8133
Revises: 9aa713db7d61
Create Date: 2026-07-07 20:50:14.030231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fcebbdf8133'
down_revision: Union[str, None] = '9aa713db7d61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_accounts',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.Enum('gmail', 'outlook', name='email_provider'), nullable=False),
    sa.Column('email_address', sa.String(length=255), nullable=False),
    sa.Column('oauth_access_token', sa.Text(), nullable=False),
    sa.Column('oauth_refresh_token', sa.Text(), nullable=False),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scopes', sa.Text(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('email_messages',
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('provider_message_id', sa.String(length=255), nullable=False),
    sa.Column('thread_id', sa.String(length=255), nullable=True),
    sa.Column('sender', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=998), nullable=False),
    sa.Column('snippet', sa.Text(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_unread', sa.Boolean(), nullable=False),
    sa.Column('ai_urgency', sa.Enum('low', 'medium', 'high', name='email_urgency'), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['email_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('email_drafts', sa.Column('account_id', sa.UUID(), nullable=True))
    op.add_column('email_drafts', sa.Column('source_message_id', sa.UUID(), nullable=True))
    # server_default backfills existing rows from Phase 3 (meeting-sourced drafts have no addresses yet).
    op.add_column(
        'email_drafts',
        sa.Column('to_addresses', sa.JSON(), nullable=False, server_default=sa.text("'[]'::json")),
    )
    op.add_column(
        'email_drafts',
        sa.Column('cc_addresses', sa.JSON(), nullable=False, server_default=sa.text("'[]'::json")),
    )
    op.add_column('email_drafts', sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'email_drafts', 'email_accounts', ['account_id'], ['id'])
    op.create_foreign_key(None, 'email_drafts', 'email_messages', ['source_message_id'], ['id'])
    # Alembic autogenerate can't detect Postgres native enum value additions — added by hand.
    op.execute("ALTER TYPE email_draft_status ADD VALUE IF NOT EXISTS 'sent'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: downgrade does not remove 'sent' from email_draft_status — Postgres has no
    # ALTER TYPE ... DROP VALUE; removing it would require recreating the enum type.
    op.drop_constraint(None, 'email_drafts', type_='foreignkey')
    op.drop_constraint(None, 'email_drafts', type_='foreignkey')
    op.drop_column('email_drafts', 'sent_at')
    op.drop_column('email_drafts', 'cc_addresses')
    op.drop_column('email_drafts', 'to_addresses')
    op.drop_column('email_drafts', 'source_message_id')
    op.drop_column('email_drafts', 'account_id')
    op.drop_table('email_messages')
    op.drop_table('email_accounts')
    # ### end Alembic commands ###
