"""add briefings

Revision ID: b97050924e84
Revises: b2f4a1c9e7d0
Create Date: 2026-07-16 13:48:46.221421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b97050924e84'
down_revision: Union[str, None] = 'b2f4a1c9e7d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('briefings',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('briefing_date', sa.Date(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('top_priorities', sa.JSON(), nullable=False),
    sa.Column('handled_keys', sa.JSON(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'briefing_date', name='uq_briefing_user_date')
    )
    op.create_index(op.f('ix_briefings_user_id'), 'briefings', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_briefings_user_id'), table_name='briefings')
    op.drop_table('briefings')
    # ### end Alembic commands ###
